version: '2.4'

services:
  app:
    build: .
    shm_size: '6gb'
    image: mshimao/pytorch1.7.1
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/root/vol
    ports:
      - '26009:6006'
      - '28891:8888'
    command: jupyter-lab
